apiVersion: v1
kind: Service

metadata:
  name: incident-app
  namespace: cloudops-dev

  labels:
    app: incident-app
    app.kubernetes.io/part-of: cloudops-platform
    environment: dev

spec:
  type: ClusterIP

  selector:
    app: incident-app

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

